### ISSUE TITLE
[BUG] Type hinting bug in new 2.0.1 with Python 3.7,3.8

### ISSUE THREAD

**Issue by JonasDev1** [youtype/awscliv2#13]
**Describe the bug**
With the latest update, type hinting features from python 3.9 have been added, which making the application no longer compatible for Python 3.7 and 3.8.

**To Reproduce**
1. Install 'awscliv2' on < Python3.9
2. Run the following command
``awsv2 --install```

**Problem solving**
The problem occurs since the refactoring at least in the [interactive_process.py](https://github.com/vemel/awscliv2/blob/main/awscliv2/interactive_process.py). It is related to the typ hinting in method signature with `Popen[bytes]`, which will only beeing supported out of the box since Py3.9.
To solve it in 3.7 and 3.8 you can import `from __future__ import annotations` (See https://github.com/python/typeshed/issues/4948)

**Comment by vemel** [comment]
Thank you for the report! Will fix today

**Comment by vemel** [comment]
Fixed and released in `2.0.2`. Please let me know if it works as it should.

**Comment by JonasDev1** [comment]
Thank you 👍 
The cli runs now on Python 3.7 successfully
