### ISSUE TITLE
MacOS Terminal Input Issue

### ISSUE THREAD

**Issue by DavidMarkMadison** [youtype/awscliv2#14]
**Describe the bug**
When I use "awscliv2 configure sso" there is a set of prompts for the aws URL link, region, etc. and the output for these prompts seems to contain Windows "^M" characters, which makes the output really odd, to the point that certain options cannot be entered.

**To Reproduce**
1. Install 'awscliv2'
2. Run the following command: "awscliv2 configure sso"

** Extra **
This output oddity does not happen with simple "awscliv2 configure" and I really the "configure sso" has a much more complicated prompting design...

I actually installyed the latest awscli v2 from amazon and that seemed to work. But, I do like the "pip install" approach here because not everyone can install from amazon (behind odd corporate networks this install may not work, and at my current clients (and most), I do not even have sudo on the machine they require me to use).

Also, this is a great tool, in general, and as others have said, I applaud you for getting it to where it is now.

**Comment by vemel** [comment]
Hello!

This is because `awscliv2 configure` is a command added by `awscliv2` wrapper and is not propagated to `aws` CLI tool itself. I will add an exception for `aws configure <service>` command.

Thank you for the report!

**Comment by vemel** [comment]
Actually, this is because `aws configure sso` is a TTY-only command.

I have just released `2.1.0`. Please try it out and let me know if it works as it should for you.
