### ISSUE TITLE
[BUG] `assume_role()` from the python module fails with `JSONDecodeError`

### ISSUE THREAD

**Issue by osego** [youtype/awscliv2#48]
**Describe the bug**
`assume_role` creates a local `stdout` variable (instance of `StringIO`) but it is NOT used in the underlying call to the CLI. Reading from the buffer returns an empty string even if the CLI call succeeded, it gets passed to `json.loads()` which in turn raises an appropriate exception.

Locally I fixed this issue by passing the local `stdout` down to `process.run()` (which required changing the signatures for `run_awscli_v2` and `_run_subprocess` to add an optional `stdout` paramater) but I deemed it too hacky to submit as a PR (although I could do so if requested).

**To Reproduce**
1. Install 'awscliv2'
2. Run the following code

```python
from awscliv2.api import AWSAPI

aws_api = AWSAPI()

aws_api.assume_role(
    profile_name="profile_name",
    source_profile="source_profile",
    role_arn="arn:aws:iam::accountid:role/OrganizationAccountAccessRole",
)
```

3. Actual behavior

The CLI result gets printed to actual stdout followed by a traceback from the error:
```python
{
    "Credentials": {
        "AccessKeyId": "...",
        "SecretAccessKey": "...",
        "SessionToken": "...",
        "Expiration": "2024-09-03T13:36:27+00:00"
    },
    "AssumedRoleUser": {
        "AssumedRoleId": "...",
        "Arn": "..."
    }
}
Traceback (most recent call last):
  File "/home/xz/code/awscliv2/scripts/fail_example.py", line 5, in <module>
    aws_api.assume_role(
  File "/home/xz/code/awscliv2/awscliv2/api.py", line 164, in assume_role
    credentials_data = json.loads(credentials_json)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rye/py/cpython@3.12.5/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rye/py/cpython@3.12.5/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/rye/py/cpython@3.12.5/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**

The call succeeds and writes appropriate data to `~/.aws/credentials`.

**Additional context**
awscliv2 version 2.3.0
binary installed with `awsv2 --install`
running in WSL2 with python managed through rye

**Comment by vemel** [comment]
Hello!

Thank you for the report. I will try to release a fix as soon as possible.

**Comment by vemel** [comment]
@osego fixed in `main`. It would be great if you could test it. Please let me know if it works as it should.

```bash
pip install https://github.com/youtype/awscliv2/archive/main.zip
```

**Comment by osego** [comment]
Thank you, works great now.
